name: 🪙 Daily Gold Price Alert

on:
  schedule:
    # Run every day at 11:00 AM IST (05:30 AM UTC)
    - cron: '30 5 * * *'
  workflow_dispatch: # Allows you to run manually from the Actions tab

jobs:
  send-alert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 lxml

      - name: Run daily gold price alert
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python main.py
